spring:
  application:
    name: proxy

catedra:
  url: "http://192.168.194.250:8080"
  token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJicnVubyIs..." # El token largo va acá

backend:
  url: "http://localhost:8081" # Para avisarle cuando Kafka diga que algo cambió
