services:
  # ==========================================
  # --- INFRAESTRUCTURA ---
  # ==========================================

  # --- Base de Datos MySQL ---
  mysql:
    image: mysql:8.0
    container_name: ticketflow-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticketflow
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- Redis (Para Sesiones) ---
  redis:
    image: redis:alpine
    container_name: ticketflow-redis
    ports:
      - "6379:6379"

  # --- Zookeeper (FALTABA ESTO) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: ticketflow-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # --- Kafka ---
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: ticketflow-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ticketflow-zookeeper:2181
      # Configuraci√≥n clave para que Backend y Proxy lo encuentren por nombre de contenedor
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://ticketflow-kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ==========================================
  # --- APLICACIONES ---
  # ==========================================

  # --- BACKEND (Spring Boot) ---
  backend:
    container_name: ticketflow-backend
    build: ./backend
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ticketflow-mysql:3306/ticketflow
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: ticketflow-redis
      # Conecta usando el nombre del contenedor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ticketflow-kafka:29092
      PROXY_URL: http://ticketflow-proxy:8080

  # --- PROXY (Spring Boot - Catedra) ---
  proxy:
    container_name: ticketflow-proxy
    build: ./proxy
    depends_on:
      kafka:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8081:8080"
    environment:
      SPRING_DATA_REDIS_HOST: ticketflow-redis
      # Conecta usando el nombre del contenedor
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ticketflow-kafka:29092
      BACKEND_URL: http://ticketflow-backend:8080

volumes:
  mysql_data:
