spring:
  data:
    redis:
      host: localhost
      port: 6379

backend:
  base-url: http://localhost:8080
  internal-token: LOCAL_INTERNAL

kafka:
  bootstrap-servers: localhost:9092
  topic-eventos: eventos-cambios
