spring:
  data:
    redis:
      host: redis-catedra
      port: 6379

backend:
  base-url: http://backend:8080
  internal-token: PROD_INTERNAL

kafka:
  bootstrap-servers: kafka:9092
  topic-eventos: eventos-cambios
