spring:
  datasource:
    url: jdbc:h2:mem:ticketflowdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

catedra:
  base-url: http://localhost:8085
  jwt-token: DEV_TOKEN
  endpoints:
    registrar: /api/v1/agregar_usuario
    login: /api/v1/authenticate

proxy:
  base-url: http://localhost:8081
  internal-token: DEV_INTERNAL
