spring:
  datasource:
    url: jdbc:postgresql://POSTGRES_HOST:5432/ticketflow
    username: ticketflow_user
    password: CHANGEME

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

catedra:
  base-url: http://SERVIDOR_REAL:PUERTO
  jwt-token: PROD_TOKEN
