spring:
  application:
    name: backend

# El Backend le pide todo al Proxy (puerto 8082 por ejemplo)
proxy:
  url: "http://localhost:8081/proxy"

# NO pongas la URL de la cátedra ni el Token aquí.
catedra:
  url: ${CATEDRA_URL:}
  token: ${CATEDRA_TOKEN:}
